eMovies/Models/Order.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace eMovies.Models
{
    public class Order
    {
        [Key]

        public int Id { get; set; }

        public string Email { get; set; }

        public string UserId { get; set; }

        [ForeignKey (nameof(UserId))]
        public ApplicationUser User { get; set; }

        public List<OrderItem> OrderItems { get; set; }


    }
}

eMovies/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using eMovies.Data;
using eMovies.Models;
using eMovies.Data.Services;
using Microsoft.AspNetCore.Authorization;
using eMovies.Data.Static;

namespace eMovies.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class MoviesController : Controller
    {
        private readonly IMoviesService _service;

        public MoviesController(IMoviesService service)
        {
            _service = service;
        }

        [AllowAnonymous]

        // GET: Movies
        public async Task<IActionResult> Index()
        {
            var allMovies = await _service.GetAllAsync(n=>n.Cinema);
            return View(allMovies);
        }
        public async Task<IActionResult>Filter(string searchString)
        {
            var allMovies = await _service.GetAllAsync(n => n.Cinema);

            if (!string.IsNullOrEmpty(searchString))
            {
                var filteredResult=allMovies.Where(n=>n.Name.Contains(searchString)|| n.Description.Contains
                (searchString )).ToList();
                return View("Index", filteredResult);
            }

            return View("Index", allMovies);
        }

        // GET: Movies/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var movieDetail = await _service.GetMovieByIdAsync(id);
            return View(movieDetail);
        }
        //GET: Movies/Edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var movieDetails=await _service.GetMovieByIdAsync(id);
            if (movieDetails == null) return View("NotFound");

            var response = new NewMovieVM()
            {
                Id = movieDetails.Id,
                Name = movieDetails.Name,
                Description = movieDetails.Description,
                Price = movieDetails.Price,
                StartDate= movieDetails.StartDate,
                EndDate= movieDetails.EndDate,
                ImageURL = movieDetails.ImageURL,
                MovieCategory = movieDetails.MovieCategory,
                CinemaId = movieDetails.CinemaId,
                ProducerId = movieDetails.ProducerId,
                ActorIds = movieDetails.Actors_Movies.Select(n => n.ActorId).ToList(),

            };

            var movieDropdownsData = await _service.GetNewMovieDropdownsValues();

            ViewBag.Cinemas = new SelectList(movieDropdownsData.Cinemas, "Id", "Name");
            ViewBag.Producers = new SelectList(movieDropdownsData.Producers, "Id", "FullName");
            ViewBag.Actors = new SelectList(movieDropdownsData.Actors, "Id", "FullName");

            return View();

        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, NewMovieVM movie)
        {
            if (id != movie.Id) return View("NotFound");
            if (!ModelState.IsValid)
            {
                var movieDropdownsData = await _service.GetNewMovieDropdownsValues();

                ViewBag.Cinemas = new SelectList(movieDropdownsData.Cinemas, "Id", "Name");
                ViewBag.Producers = new SelectList(movieDropdownsData.Producers, "Id", "FullName");
                ViewBag.Actors = new SelectList(movieDropdownsData.Actors, "Id", "FullName");
                return View(movie);

            }
            await _service.UpdateMovieAsync(movie);
            return RedirectToAction(nameof(Index));
        }
        // GET: Movies/Create
        public async Task<IActionResult> Create()
        {
            var movieDropdownsData = await _service.GetNewMovieDropdownsValues();

            ViewBag.Cinemas = new SelectList(movieDropdownsData.Cinemas, "Id", "Name");
            ViewBag.Producers = new SelectList(movieDropdownsData.Producers, "Id", "FullName");
            ViewBag.Actors = new SelectList(movieDropdownsData.Actors, "Id", "FullName");

            return View();

        }
        [HttpPost]
        public async Task<IActionResult>Create(NewMovieVM movie)
        {
            if (!ModelState.IsValid)
            {
                var movieDropdownsData = await _service.GetNewMovieDropdownsValues();

                ViewBag.Cinemas = new SelectList(movieDropdownsData.Cinemas, "Id", "Name");
                ViewBag.Producers = new SelectList(movieDropdownsData.Producers, "Id", "FullName");
                ViewBag.Actors = new SelectList(movieDropdownsData.Actors, "Id", "FullName");
                return View(movie);

            }
            await _service.AddNewMovieAsync(movie);
            return RedirectToAction(nameof(Index));
        }


        /*
                // GET: Movies/Details/5
                public async Task<IActionResult> Details(int? id)
                {
                    if (id == null)
                    {
                        return NotFound();
                    }

                    var movie = await _context.Movies
                        .Include(m => m.Cinema)
                        .Include(m => m.Producer)
                        .FirstOrDefaultAsync(m => m.Id == id);
                    if (movie == null)
                    {
                        return NotFound();
                    }

                    return View(movie);
                }

                // GET: Movies/Create
                public IActionResult Create()
                {
                    ViewData["CinemaId"] = new SelectList(_context.Cinemas, "Id", "Id");
                    ViewData["ProducerId"] = new SelectList(_context.Producers, "Id", "Id");
                    return View();
                }

                // POST: Movies/Create
                // To protect from overposting attacks, enable the specific properties you want to bind to.
                // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
                [HttpPost]
                [ValidateAntiForgeryToken]
                public async Task<IActionResult> Create([Bind("Id,Name,Description,Price,ImageURL,StartDate,EndDate,MovieCategory,CinemaId,ProducerId")] Movie movie)
                {
                    if (ModelState.IsValid)
                    {
                        _context.Add(movie);
                        await _context.SaveChangesAsync();
                        return RedirectToAction(nameof(Index));
                    }
                    ViewData["CinemaId"] = new SelectList(_context.Cinemas, "Id", "Id", movie.CinemaId);
                    ViewData["ProducerId"] = new SelectList(_context.Producers, "Id", "Id", movie.ProducerId);
                    return View(movie);
                }

                // GET: Movies/Edit/5
                public async Task<IActionResult> Edit(int? id)
                {
                    if (id == null)
                    {
                        return NotFound();
                    }

                    var movie = await _context.Movies.FindAsync(id);
                    if (movie == null)
                    {
                        return NotFound();
                    }
                    ViewData["CinemaId"] = new SelectList(_context.Cinemas, "Id", "Id", movie.CinemaId);
                    ViewData["ProducerId"] = new SelectList(_context.Producers, "Id", "Id", movie.ProducerId);
                    return View(movie);
                }

                // POST: Movies/Edit/5
                // To protect from overposting attacks, enable the specific properties you want to bind to.
                // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
                [HttpPost]
                [ValidateAntiForgeryToken]
                public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,Price,ImageURL,StartDate,EndDate,MovieCategory,CinemaId,ProducerId")] Movie movie)
                {
                    if (id != movie.Id)
                    {
                        return NotFound();
                    }

                    if (ModelState.IsValid)
                    {
                        try
                        {
                            _context.Update(movie);
                            await _context.SaveChangesAsync();
                        }
                        catch (DbUpdateConcurrencyException)
                        {
                            if (!MovieExists(movie.Id))
                            {
                                return NotFound();
                            }
                            else
                            {
                                throw;
                            }
                        }
                        return RedirectToAction(nameof(Index));
                    }
                    ViewData["CinemaId"] = new SelectList(_context.Cinemas, "Id", "Id", movie.CinemaId);
                    ViewData["ProducerId"] = new SelectList(_context.Producers, "Id", "Id", movie.ProducerId);
                    return View(movie);
                }

                // GET: Movies/Delete/5
                public async Task<IActionResult> Delete(int? id)
                {
                    if (id == null)
                    {
                        return NotFound();
                    }

                    var movie = await _context.Movies
                        .Include(m => m.Cinema)
                        .Include(m => m.Producer)
                        .FirstOrDefaultAsync(m => m.Id == id);
                    if (movie == null)
                    {
                        return NotFound();
                    }

                    return View(movie);
                }

                // POST: Movies/Delete/5
                [HttpPost, ActionName("Delete")]
                [ValidateAntiForgeryToken]

eMovies/Controllers/OrdersController.cs
using eMovies.Data.Cart;
using eMovies.Data.Services;
using eMovies.Data.Static;
using eMovies.Data.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace eMovies.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly IMoviesService _moviesService;
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrdersService _ordersService;

        public OrdersController(IMoviesService moviesService, ShoppingCart shoppingCart, IOrdersService ordersService)
        {
            _moviesService = moviesService;
            _shoppingCart = shoppingCart;
            _ordersService = ordersService; 
        }

        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);

            var orders = await _ordersService.GetOrdersByUserIdAndRoleAsync(userId, userRole);
            return View(orders);
        }

        public IActionResult ShoppingCart()
        {

            var items = _shoppingCart.GetShoppingCartItems();

            _shoppingCart.ShoppingCartItems = items;


            var response = new ShoppingCartVM()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };

            return View(response);
        }
        public async Task<IActionResult> AddItemToShoppingCart(int id)
        {
            var item = await _moviesService.GetMovieByIdAsync(id);
            if (item != null)
            {
                _shoppingCart.AddItemToCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }
        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item = await _moviesService.GetMovieByIdAsync(id);
            if (item != null)
            {
                _shoppingCart.RemoveItemFromCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmailAddress = User.FindFirstValue(ClaimTypes.Email);

            await _ordersService.StoreOrderAsync(items, userId, userEmailAddress);

            await _shoppingCart.ClearShoppingCartAsync();

            return View("OrderCompleted");


        }
    }
}

eMovies/Views/Orders/Index.cshtml
@model List<Order>

@{
    ViewData["Title"] = "All orders";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4>List of all your orders</h4>
        </p>

        <table class="table">
            <thead>
                <tr>
                    <th>Order ID</th>
                    <th>Items</th>
                    <th>Total</th>

                    @if(User.Identity.IsAuthenticated && User.IsInRole("Admin")){
                        <th>User</th>
                    }
                    
                </tr>
            </thead>
            <tbody>
                @foreach (var order in Model)
                {
                    <tr>
                        <td class="align-middle">@order.Id</td>
                        <td class="align-middle">
                            <ul style="list-style-type:none">
                                @foreach (var item in order.OrderItems)
                                {
                                    <li>
                                        <div class="alert alert-info" role="alert">
                                            <span class="badge bg-success">@item.Amount</span> [@item.Price.ToString("c")] - @item.Movie.Name
                                        </div>
                                    </li>
                                }
                            </ul>
                        </td>
                        <td class="align-middle">
                            @order.OrderItems.Select(m => m.Movie.Price * m.Amount).Sum().ToString("c")
                        </td>
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                          <td class="align-middle">@order.User.FullName</td>
                        }
                 </tr>
                } 
            </tbody>
        </table>

    </div>
</div>

eMovies/Views/Orders/OrderCompleted.cshtml
<div class="row">
    <div class="col-md-6 offset-3 alert-success text-center">
        <h2>Order completed successfully</h2>
        <p>You can check all your orders in the Orders section of your profile</p>
        <hr/>
        <p>Thank you!</p>
    </div>
</div>

eMovies/Views/Orders/ShoppingCart.cshtml
@using eMovies.Data.ViewModels;
@model ShoppingCartVM

@{
    ViewData["Title"] = "Shopping cart summary";
}
   <div class="row">
       <div class="col-md-8 offset-2">
           <div class="text-center">
               <h2>You shopping cart summary</h2>
           </div>
            <table class="table">
                <thead>
                    <tr>
                        <th>Selected amount</th>
                        <th>Movie</th>
                        <th>Price</th>
                        <th>Subtotal</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                @foreach (var item in Model.ShoppingCart.ShoppingCartItems)
                {
                        <tr>
                            <td class="align-middle">@item.Amount</td>
                            <td class="align-middle">@item.Movie.Name</td>
                            <td class="align-middle">@item.Movie.Price.ToString("c")</td>
                            <td class="align-middle">@((item.Amount * item.Movie.Price).ToString("c"))</td>
                            <td class="align-middle">
                                <a class="text-danger"asp-controller="Orders"asp-action="RemoveItemFromShoppingCart"
                            asp-route-id="@item.Movie.Id">
                             <i class="bi bi-cart-dash"></i>
                         </a>
                            |
                             <a class="text-success"asp-controller="Orders"asp-action="AddItemToShoppingCart"
                            asp-route-id="@item.Movie.Id">
                                 <i class="bi bi-cart-plus"></i>
                             </a>

                            </td>
                        </tr>
                }
                 </tbody>
                <tfoot> 
                    <tr>
                        <td colspan="2"></td>
                        <td><b>Total:</b></td>
                        <td>
                        @Model.ShoppingCartTotal.ToString("c")

                        </td>
                        <td></td>
                    </tr>
                </tfoot>

            </table>
            <div class="text-center">
                <div class="btn-group">
                  @*  <a class="btn btn-outline-primary" asp-action="CompleteOrder">
                        Complete order
                    </a>*@
                    <div id="paypal-btn"></div>

                    <span style="padding:5px"></span>

                    <a class="btn btn-outline-success" asp-controller="Movies"asp-action="Index">
                        Add more items
                    </a>
                </div>


            </div>
       </div>
   </div>

@section Scripts{

    <script src="https://www.paypalobjects.com/api/checkout.js"></script>

    <script>
        let _total=@Html.Raw(Model.ShoppingCartTotal);
        paypal.Button.render({
            //Configure environment
            env: 'sandbox',
            client: {
                sandbox: 'AfcrTcTp6AlyzFlzC3aFqxDYDlVZlpizG--mv7NP1H8Ci5_WX5c8qIx9HujpWiIIhvJjJXWb6pfk92j4'
            },
            //Customize button
            locale: 'en_US',
            style: {
                size: 'small',
                color: 'gold',
                shape: 'pill'
            },
            commit: true,
            //Set up a payment
            payment: function (data, actions) {
                return actions.payment.create({
                    transactions:[{
                        amount:{
                            total: _total,
                            currency:'USD'
                        }
                    }]
                    
                });
            },
            //Execute the payment
            onAuthorize: function (data, actions) {
                return actions.payment.execute().then(function(){
                    var url = '@Url.Action("CompleteOrder","Orders",new {})';
                    window.location.href=url;
                })
            }
        }, '#paypal-btn')
    </script>
}